### ISSUE TITLE
Mongol hel

### ISSUE THREAD

**Issue by ganbaaelmer** [bayartsogt-ya/bayartsogt-ya#1]
Sain baina uu
Mongol hel deer sentence similarity Bert -r hiij baisanuu?
Zuvluguu baina uu?
jishee github repo bnuu?
thx

**Comment by bayartsogt-ya** [comment]
hi!

> Mongol hel deer sentence similarity Bert -r hiij baisanuu?

Яг нарийн туршаагүй гэхдээ шууд feature extraction ажиллахгүй гэдгийг мэдэж байна.


> Zuvluguu baina uu?

Заавал advanced юм ашиглах гээд байгаа юу? Энгийн аргуудаар эхлээд сайн baseline тай болсон нь дээр байх аа. Sentence similarity-г зүгээр үгээр нь тодорхойлж болно ш дээ.

> jishee github repo bnuu?

BERT-г иймэрхүү байдлаар finetune хийж болно ш дээ хө https://keras.io/examples/nlp/semantic_similarity_with_bert/

Монгол хэлний моделоо энэ мөр дээр сольж болно.
```python
self.tokenizer = transformers.BertTokenizer.from_pretrained(
    "bert-base-uncased", do_lower_case=True
)
```

**Comment by ganbaaelmer** [comment]
model = SentenceTransformer('LaBSE')
engeed bolchloo thx.
